### ISSUE TITLE
keptn presentation at tag-app-delivery meeting

### ISSUE THREAD

**Issue by thschue** [cncf/tag-app-delivery#132]
As part of the review, keptn should be presented in one of the next TAG meetings

**Comment by jetzlstorfer** [comment]
We would like to present on August, 4th. Is that possible?

**Comment by jetzlstorfer** [comment]
Is there any update on this?

**Comment by joshgav** [comment]
Notes from today's presentation ([original](https://docs.google.com/document/d/1OykvqvhSG4AxEdmDMXilrupsX2n1qCSJUWwTc3I7AOs)):

- Proposal for incubation: https://github.com/cncf/toc/pull/670
- Links: https://keptn.sh, https://github.com/keptn/keptn
- Motivation: Thousands of lines of automation code (shell scripts), different in each team, must be integrated into pipeline runner. 
- How does Keptn solve? Break big pipelines into many small tasks and abstract these tasks as opaque units; relate tasks and executions together via events and environments.
  - Opinionated set of common tasks - build, deploy, release, etc.
  - Abstracts the implementation of a task from its use in a declared pipeline
  - One task type is to check compliance to SLOs and SLIs - "Quality Gates"
- Adopters:
  - Raiffeisen Software - release validation using quality gates
  - Vitality - deploy and test shared services in many tenants as quality gates
  - Kitopi - evaluate resiliency - availability under load and chaos - of deployment
- Integration with other CNCF projects
  - cloud events - all events are structured per this standard
  - Artifact Hub - publish Keptn artifacts there
  - Tekton (CDF) - build and deploy with Tekton, coordinate other activities with Keptn
  - others: LitmusChaos, Argo, Helm, Crossplane, Prometheus, Slack, https://github.com/keptn-contrib, https://github.com/keptn-sandbox
- Progress since sandbox (see deck):
  - implement multi-cluster support - separate control plane from execution plane
  - implement closed-loop remediation - reconciliation rather than one-off apply
- Community
  - stats - see deck
  - graduated 3 mentees
- resources - https://keptn.sh/resources
- roadmap - https://github.com/orgs/keptn/projects/1
  - plan to integrate CDF SIG Events events (https://github.com/cdfoundation/sig-events)
- Q's
  - API stability, version updates? A: Always provide an upgrade guide, try to avoid breaking changes. A: Deprecated APIs still operate for a while.
  - Is it for quality assurance, or general build/test/deploy tasks?
    - Keptn does orchestration based on events, can orchestrate many task runner systems like Tekton or a custom task runner by subscribing to events
    - Keptn does quality assurance tasks itself, QA is a first-class capability of Keptn
  - Is this simpler than Argo Workflows, Tekton?
    - Tekton is not opinionated, Keptn provides opinionated automation sequences
    - Clarify how to add an integration with a task runner service like Tekton. A: <https://keptn.sh/docs/0.8.x/integrations/how_integrate/>

**Comment by joshgav** [comment]
Closing this as the meeting is done, ongoing review continues in #131.
