### ISSUE TITLE
Definition of an operator

### ISSUE THREAD

**Issue by AloisReitbauer** [cncf/tag-app-delivery#15]
The TOC asked us to work on a definition for "What an operator is" Let us use this as a discussion thread.

**Comment by ebcarty** [comment]
From the email thread...
- An Operator is an application-specific controller that extends the Kubernetes API to create, configure, and manage instances of complex (stateful) (applications) workloads on behalf of a Kubernetes user. It builds upon the basic Kubernetes resource and controller concepts but includes domain or application-specific knowledge to automate common tasks.

- An Operator is a Kubernetes API extension to automate domain-specific workflow actions through declarative definitions.

- An operator is a platform extension that creates, configures, and manages the lifecycle of workloads.
- A Kubernetes operator is an extension to the Kubernetes API that builds upon the basic Kubernetes resource and controller concepts but includes domain-specific knowledge to automate common tasks for a given workload.

- An operator is software that manages routine procedures and lifecycle operations of workloads.
- A Kubernetes operator is a controller that manages routine procedures and lifecycle operations of workloads.

Will try to update as the conversation continues.

**Comment by ebcarty** [comment]
![image](https://user-images.githubusercontent.com/13952816/68578334-a1521180-0426-11ea-8fa1-cc6df7e8186a.png)

The [OperatorHub](https://operatorhub.io/) has defined different [Capability Levels](https://github.com/operator-framework/operator-sdk#operator-capability-level) to help categorize the use-case and scope of the available operators.

**Comment by AloisReitbauer** [comment]
Working document can be found here: https://docs.google.com/document/d/1daXHyR2yG5ArjO1PO83v4a0fmLCLo2kYNT3TwGZksng/edit#heading=h.10b2c6uoywdk

**Comment by mkorbi** [comment]
@AloisReitbauer what is actually the target we want to reach? Like the cloud native defenition https://github.com/cncf/toc/blob/master/DEFINITION.md or with more explenation around it like a description/specification?

**Comment by thschue** [comment]
In the last few weeks, we tried to get a definition what an operator is, of which components it consists and how they play together. Afterwards we discussed about capabilities of an operator. We thought that it would be a better idea to talk about the capabilities of operators than about capability levels. Currently we defined following capabilities:

* Install an application  / take ownership on an application
* Upgrade an application
* Backup
* Recovery from Backup (Restore)
* Auto-Remediation 
* Monitoring/Metrics - Observability (of the Operator != of the application)
* Scaling
* Auto-Scaling
* Uninstalling
* Auto-Configuration tuning

More detailed descriptions and criteria of these capabilities are currently WIP and the state is in the [Working Document](https://docs.google.com/document/d/1daXHyR2yG5ArjO1PO83v4a0fmLCLo2kYNT3TwGZksng/edit#heading=h.10b2c6uoywdk).

After these definitions are written down, we want to create example implementations of these capabilities for the AppDelivery Demo Application ([PodTato-Head](https://github.com/cncf/podtato-head)). Using these examples, we want to illustrate/describe how operators for different use-cases could look like and which value they provide to users.

**Comment by coderanger** [comment]
The definition I use when working with folks on operators, reworded to be slightly more specific:

"An operator is zero or more CustomResourceDefintions (i.e. custom types) and one or more custom convergent control loops (custom controllers) packaged together to achieve a constructive purpose."

This leaves all all mention of specific features beyond "is convergent" and "does something useful". Arguably "packaged" in that could be swapped for something else, since packaging itself is also a bit of a definitional quagmire.

**Comment by grzesuav** [comment]
I would say that operator is an application communicating with kubernetes API directly, one way or another. It does not require to introduce any additional CRD (can work on base API), can just read or just write to k8s API.

But this is also vague explanation - like does prometheus service discover is an operator ? It communicates with API. however I would not say it is an operator.

**Comment by coderanger** [comment]
Also for those that don't read a lot about weird gaming paratext, a useful model for this might be the Berlin Interpretation on the definition of "Roguelike" (http://www.roguebasin.com/index.php?title=Berlin_Interpretation).

Their take was that no single definition text would ever fully capture what "Roguelike" meant to everyone without being so vague as to be useless, so instead they worked out a set of high-value and low-value factors and the more of them that a game has, the more "Roguelike" (or more likely to be considered a "Roguelike") it is. I think this model would work well here too, since the outer edges of "custom control loops that talk to the Kubernetes API" definitely gets very gray area. Like I would argue that external-dns is an operator but what about addons-manager? That's a while loop in bash that calls kubectl apply, does that count as a convergent control loop? :)

**Comment by thschue** [comment]
As Version 1.0 of the White Paper is finished (https://github.com/cncf/tag-app-delivery/blob/master/operator-wg/whitepaper/Operator-WhitePaper_v1-0.md), this issue is done. Thanks to everyone for your contributions!
