### ISSUE TITLE
[GitOps] give WG chairs access to create events on CNCF community tag-app-delivery group

### ISSUE THREAD

**Issue by scottrigby** [cncf/tag-app-delivery#155]
Can [GitOps WG](https://github.com/cncf/tag-app-delivery/tree/master/gitops-wg) chairs please be granted access to creating events on https://community.cncf.io/tag-app-delivery/?

GitOps WG chairs:
- [ ] @murillodigital 
- [x] @scottrigby 
- [ ] @todaywasawesome

See:
- https://github.com/gitops-working-group/gitops-working-group/issues/70
- https://github.com/gitops-working-group/gitops-working-group/issues/66

**Comment by thschue** [comment]
Please let me know which events we should add. Thank you!

**Comment by roberthstrand** [comment]
I would help out with events date and times, but I haven't had the chance to be in a gitops-wg related meeting for a while. Since we only have relatively static and repetitive events, working through the chairs or tech leads shouldn't be too difficult to manage. However, if there was a need to add a lot of new events then access would be the way to go. Agree, @scottrigby?

**Comment by joshgav** [comment]
Closing as stale. Let's revisit CODEOWNERship in this repo.
