### ISSUE TITLE
Platforms Glossary v2

### ISSUE THREAD

**Issue by abangser** [cncf/tag-app-delivery#485]
Based on some feedback in the maturity model calls and reviews we are identifying a need for further investment into the Platforms glossary. This was originally a late addition to the work we did on the white paper and it is proving both useful and widely referenced so it is worth us making sure it reflects what the group is currently feeling on each of these terms.

**Comment by abangser** [comment]
cc/ @joshgav @AdminTurnedDevOps and @earth2marsh

This is likely to take shape post KubeCon Chicago but I know y'all are thinking on this so want to be sure you know it is captured and top of the todos!

**Comment by AdminTurnedDevOps** [comment]
Thank you! Please let me know if there's anything I can do to help out here. I'll be at KubeCon as well, so happy to connect there!

**Comment by abangser** [comment]
As discussed on the last WG call, here is a google doc where we can collaborate on the glossary updates: https://docs.google.com/document/d/1qYXasDys7gSPcMcTNVY9wZVXESXbMVz5KpjaLu-WYBo/edit

**Comment by joshuabezaleel** [comment]
@abangser I was thinking, should we add `Platform Orchestrator` to the glossary? I myself haven't heard about this term before until when I gave the talk with Giri on KubeCon NA 23 on our IDP, one of the attendees asked about what's the platform orchestrator we're using, which turns out it was the one that we built ourselves in-house.

And also seems like all other online resources are already mentioning this term.
- https://internaldeveloperplatform.org/platform-orchestrators/
- vendor like humanitec
- and thoughtworks (https://www.thoughtworks.com/radar/techniques/platform-orchestration) on their radar

Or this can be mentioned side-by-side with the current [Platform capability provider](https://tag-app-delivery.cncf.io/wgs/platforms/glossary/#platform-capability-providers) (?) since I think there's overlap there as well.

**Comment by abangser** [comment]
Absolutely seems like a good idea! I also wonder if `FleetOps` or `Fleet Operations` which came up in a previous call may be worth adding in? We have to basically decide if we want to try and push some of the "newer" vocab or stay more reactive to what is used.

That being said, I would agree with you that platform orchestrator fits the "already being used" category anyways since it is in the TW radar!

**Comment by abangser** [comment]
> @abangser I was thinking, should we add Platform Orchestrator to the glossary?

@joshuabezaleel I have taken a stab here: https://docs.google.com/document/d/1qYXasDys7gSPcMcTNVY9wZVXESXbMVz5KpjaLu-WYBo/edit

Would love your feedback and ideas on this and other items if you have the time!

**Comment by earth2marsh** [comment]
Thanks for the suggestion--given that neither the whitepaper nor the maturity model use `platform orchestrator`,  let's hold this for consideration in a future update (v3 or later)? Bonus is that by then we might also see better consensus around what the term means as that space matures! :)

**Comment by joshgav** [comment]
Hi folks! Now that #545 has been merged do you think we should close this issue? We could create individual issues to discuss new/revised entries in the model, such as one for Platform Orchestrator. WDYT?

**Comment by abangser** [comment]
I agree @joshgav, we could even open one for v3 which opens the door for new items but may just leave it to the community to drive. Will close now and focus on getting the translation ones done as people get to them!

**Comment by joshuabezaleel** [comment]
Hi @abangser @earth2marsh , so sorry for the really late reply. Now that I moved to a company that doesn't use GitHub, it's very rare for me to open it and hence making me missed this reply 😞 

> > @abangser I was thinking, should we add Platform Orchestrator to the glossary?
> 
> @joshuabezaleel I have taken a stab here: https://docs.google.com/document/d/1qYXasDys7gSPcMcTNVY9wZVXESXbMVz5KpjaLu-WYBo/edit
> 
> Would love your feedback and ideas on this and other items if you have the time!

@abangser I tried to access the link that you gave but couldn't find the change that you mentioned, perhaps it was because I  just accessed it now and it has been quite a while since the time you modified the document. So sorry 😞 Do let me know if you have that in any other place that I can take a look at. 

> Absolutely seems like a good idea! I also wonder if `FleetOps` or `Fleet Operations` which came up in a previous call may be worth adding in? We have to basically decide if we want to try and push some of the "newer" vocab or stay more reactive to what is used.
> 
> That being said, I would agree with you that platform orchestrator fits the "already being used" category anyways since it is in the TW radar!

@abangser Your comment was on the Jan 5 so I assume it was the 2023-12-12 call that you mentioned (since we didn't have the 2023-12-26 one)? I think I missed this conversation back then. I'll try to hear the recording again for the meeting for the `FleetOps` and `Fleet Operations` one! 


> Thanks for the suggestion--given that neither the whitepaper nor the maturity model use `platform orchestrator`, let's hold this for consideration in a future update (v3 or later)? Bonus is that by then we might also see better consensus around what the term means as that space matures! :)

> Hi folks! Now that https://github.com/cncf/tag-app-delivery/pull/545 has been merged do you think we should close this issue? We could create individual issues to discuss new/revised entries in the model, such as one for Platform Orchestrator. WDYT?

@earth2marsh @joshgav Makes sense, that works! We can wait for the v2 one to be published and then we can create new issue for the v3 one or just let me know the perfect time to create new issue for the v3. Thank you lots, folks!

**Comment by abangser** [comment]
Glad to see you back here @joshuabezaleel. An no stress on the delay, life happens and as you can see, we just keep you updated as we move forward!

The missing details in the doc is indeed because the doc has moved on. Per the last point, we decided to keep the diff mostly formatting (or refinining existing terms) in this version and open the door for a v3 in quick succession for terms like platform orchestrator, fleetops and more.

As for fleet ops in specific, I believe it was mentioned in one of the meetings but I don't actually remember which one 🙈

But the good folks at JetStack Consult were the ones who introduced it and here is a blog about it: https://venafi.com/blog/introduction-to-fleetops-standardizing-kubernetes-operating-models/
