### ISSUE TITLE
Platform Engineering Stack/Whitepaper

### ISSUE THREAD

**Issue by AdminTurnedDevOps** [cncf/tag-app-delivery#489]
After discussion with members of the #wg-platforms group, I would like to propose an idea on either a third paper or an addition to an existing Platform Engineering paper.

The idea is for something that's more engineering-focused. A paper that goes over Platform Engineering from an engineering/architecture/tools/overall implementation perspective.

As of right now, what I'm thinking is something around particular stacks. One of the biggest things I see in Platform Engineering right now (well, tech in general... but, ya know, one problem at a time) is engineers want to dive into particular specialties (like Platform Engineering), but they have ZERO idea where to start because there are so many tools, platforms, and procedures... and a lot of the tools in various categories are doing the same thing, which causes more confusion.

Therefore, I'd love to create a paper, or add to a paper, a few different stacks that engineers can use, architecture references, the "why" behind it, and something that's overall engineering-focused for the practitioners. 

For more information, please reference the following Slack threads:
- https://cloud-native.slack.com/archives/C020RHD43BP/p1698688730310209
- https://cloud-native.slack.com/archives/C020RHD43BP/p1698679641506099

**Comment by abangser** [comment]
Thank you for raising this idea! I would love to hear a bit more about how you define "stacks". 

For example, I could imagine [LAMP](https://en.m.wikipedia.org/wiki/LAMP_(software_bundle)) as an example from the software world which focuses on specific tools.

In contrast I can also think about the patterns purposed by all the debates on skinny or fat models or controllers (e.g. [this blog] (https://thoughtbot.com/blog/skinny-controllers-skinny-models) and other pattern based discussions.

They both _could_ answer the challenges your raising that engineers face, but in very different ways.

**Comment by AdminTurnedDevOps** [comment]
Hey @abangser :)

Thanks for the questions! Definitely makes sense.

The way I see stacks is exactly what you describe, the LAMP stack. The cool thing about the LAMP stack is it sets a starting point/standard, but you can also swap out. For example, M is for MySQL, but there are a lot of "LAMP" stacks that have Postgres.

To your suggestion on Slack, this definitely overlaps a lot with CNOE. After diving into CNOE, it's clear that the project is creating a particular stack to use from a best practices perspective, but the goal with CNOE is also to provide best practices/standards and not just an app stack.

I primarily see this as a few things:
1. A great starting point for engineers to choose what they should be using in terms of tool/platform use.
2. To define some standards around tooling with Platform Engineering.

Some of the biggest questions I get asked every week are "What tool should I use?" or "Why should I try this tool/platform out?". The questions don't stem from the lack of tooling/platform capability, but from there being a lot of tools/platforms available to choose from. The ability to pick and choose what you want to use is great, but it comes down to a "you don't know what you don't know until you know" conversation.

**Comment by abangser** [comment]
That makes sense, thanks for the more detail @AdminTurnedDevOps (and great meeting you this week at KubeCon!).

As we discussed on Monday, I think it would be best to tackle this type of big concept with a more progressive format. While we haven't yet determined a process, I am thinking we can try something out here.

My suggestion would be to start with some blog posts and progress through the topics until we feel we have either met our goals or need a bigger investment.

My suggestion would be to start with a blog post about why the concept is important to talk about. This would be sort of laying out the content of your last post here and lay the foundation for why this is something the WG should invest further in.

From there we can see what the next topic is based on the initial blog content, though my initial idea would be to write a post on how to evaluate different technology. This would set us up for further posts where we actually use that evaluation structure to generate examples of stacks. 

How does that sound? Is there a better path you can suggest while prioritising smaller chunks of work that "show our work" rather than just the conclusion doc?

**Comment by AdminTurnedDevOps** [comment]
@abangser this totally makes sense!

starting with the smaller blogs and then ramping up.

in terms of other outlets, I’m working on this as we speak. I’ve been pushing out a ton of posts and content on LinkedIn about Platform Engineering, so I’d be happy to discuss how that can help as well. If you’d like, I’m happy to show you what I’ve been putting out (which has been getting some great traction) and see how we can tie it in with the working group?

**Comment by abangser** [comment]
In trying to get alignment on current WG priorities, I am going to suggest we close this topic. But before doing so, I want to give 1 week for anyone who is interested to revive the focus on this, else we can reopen in the future when we have the right people/energies to commit to this topic (or create an associated blog post).

Thanks!

**Comment by abangser** [comment]
Per my last message, I am closing for now but am happy to reopen this conversation if it becomes higher priority / has a sponsor to drive it!
