### ISSUE TITLE
Kubecon Paris (March 2024) planning

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#498]
This issue is to track plans for Kubecon Paris in March 2024. Let us know what you think we should do and what you can help with!

Things we've done the past few Kubecons and which we'd like to continue:

- Booth in project pavilion for meetups
- Lightning talk sessions on our governed projects and new ideas
- Project meeting on project meeting day
- Conference sessions about the TAG and WGs
- Announcements of new papers and initiatives
```[tasklist]
### Tasks
- [x] Request Project Opportunities (Booth, Lightning Talk)
- [x] Request Conference Session for TAG
```

**Comment by angellk** [comment]
Thanks for kicking this off @joshgav - it'd be good to have a retro from KubeCon Chicago in order to help plan better for Paris. Can we dedicate one of the TAG App Delivery calls to this?

**Comment by joshgav** [comment]
I was thinking we'd spend 20 minutes in the call this Wednesday gathering feedback.

**Comment by abangser** [comment]
I may not be able to make the call this week, but I would like to propose that we create a schedule that is based on x days/weeks before the event that we can iterate on and use for any upcoming kubecons. For example, 10 weeks out we create the issue, 8 weeks out we request a booth, 6 weeks out we request a sponsor for booth print outs etc etc etc.

Not sure where to capture that so just wanted to put it down here before it was lost!

**Comment by krumware** [comment]
Thought: With the focus on interviews, it may be fun/helpful/beneficial to host several interviews at the booth (perhaps alongside or in lieu of some of the lightning talks that are typically scheduled)

**Comment by techmaharaj** [comment]
I'd like to assist with the following:
- lighting talk at the booth/meeting
- panel discussion/moderation at the booth/meeting
- Marketing/Social Media/Content related planning

I'll be around in the calls to jump in for any of these.

**Comment by Saim-Safdar** [comment]
I'd like to assist with the following:

- I can help co-ordinate the messaging with the guest I'm interviewing for my podcast
- Co-ordinate the messaging with the attendees on MultitenancyCon.
- Assist with setting up time for speakers presenting in the MultitenancyCon, we have some good enterprise guests attending the conference. 
- Echoing messaging on social media during the conference.

I'll be around in the calls to jump in for any of these.

**Comment by dstengle** [comment]
Some ideas from TAG App delivery meeting today:

- Having an abridged survey form for walk-ups to the booth in Paris
  - Align this with the interview data to be brief but contain signals for followup
- Have some sort of interview space set aside for walk-ups

**Comment by techmaharaj** [comment]
Hi @lianmakesthings just circling to check if we're having a booth and if you know when that would be. Some of us at the wg-platforms wanted to plan a few things, so wanted to know if we have a booth so that we can plan accordingly.

**Comment by lianmakesthings** [comment]
Hi @techmaharaj, yes we will have a booth for half-days on all three KubeCon days.
We have not yet set an agenda though.
Could you share what you had planned, so we can keep that in mind?

**Comment by techmaharaj** [comment]
> Hi @techmaharaj, yes we will have a booth for half-days on all three KubeCon days. We have not yet set an agenda though. Could you share what you had planned, so we can keep that in mind?

So one of the groups is working on [conducting some interviews around platform engineering](https://github.com/cncf/tag-app-delivery/issues/553#issue-2127480559) and was wondering about ways to evangelize it, including doing some on-booth interactions, etc.

**Comment by lianmakesthings** [comment]
Commenting to track the Platforms WG coffee in this issue https://github.com/cncf/tag-app-delivery/issues/557

**Comment by lianmakesthings** [comment]
Hey everyone,
thanks for your patience while we got the ball rolling on our KubeCon plans.
You can find our **preliminary agenda [here](https://docs.google.com/document/d/1P5m0uqzAtkwd2-J6aCCvrAB2LEx5OMzLfZwKB-YbTGE/edit)**

### The tl,dr of it

🕐 We will have a booth at the project pavilion for a full day on Wednesday, and half days Thursday and Friday.

⚡ At our booth, we will have space for lightning talks which you can **submit via [this form](https://forms.gle/VxtPJs3t8Ezfnq928)**

📝  Note the following requirements to submit a topic:
- The topic should be relevant to the TAG app-delivery. If in doubt, refer to [our charter](https://tag-app-delivery.cncf.io/)
- When submitting project presentations, keep in mind that we will only accept CNCF projects, or projects submitted to CNCF sandbox.
- Lightning talks will be a maximum of 10 minutes, a computer display can not be guaranteed.
The call for proposals ends March 3rd. If your talk is accepted, we will notify you by March 9th. If you did not hear back from us, your submission has unfortunately not been accepted.

📈  Since we will not have a space for the project meeting on Tuesday this year, we are thinking how we could have a public project meeting at our booth Wednesday morning. Ideas, suggestions & concerns welcome.

👥  Additionally, we have set aside Open Booth time, which we want to use to feature our individual WGs. Ideally we would have WG chairs present at the time (currently Wednesday 12 - 13, Thursday 12:30 - 13:30, Friday 10:30 - 12:30).

❓ There’s also still an open question about a table provided by the CNCF in the expo area for the TAGs, where we may be able to organise Birds of a Feather sessions. We're waiting CNCF to get back to us


### What you can do to help:
✅ Submit a lightning talk
✅ Share the schedule
✅ Share the Call for submissions
✅ Help us out with booth duty and add yourself to [the schedule]( https://docs.google.com/spreadsheets/d/1eIVgSb4PQF3FaDA6pwJ02LfM1ai0koWd0b6YWJ_abgU/edit?usp=sharing)
✅ Let us know about any other events & activities in or around KubeCon that we might want to add to the agenda.

**Comment by dstengle** [comment]
Is there any alternate registration track for those of us coming to support the platform day and the booth presence for the WG?

**Comment by lianmakesthings** [comment]
> Is there any alternate registration track for those of us coming to support the platform day and the booth presence for the WG?

If you are referring to the KubeCon registration itself: Not to my knowledge, no.

**Comment by thschue** [comment]
Delivered everything, closing this issue
