### ISSUE TITLE
Platform Engineering Maturity Model: is InnerSource part of 'Level 4, Optimizing — Enabled ecosystem'

### ISSUE THREAD

**Issue by jkleinlercher** [cncf/tag-app-delivery#532]
Hi, first of all I am very thankful for the platform maturity model! Great work! When we applied an innersource model, where people outside of the platform team can contribute to the platform, is this already then a part of "level 4 - enabled ecosystem" or is this still leve 3? what do you think?

**Comment by menzenski** [comment]
In one sense I think that
> we applied an innersource model, where people outside of the platform team can contribute to the platform

maps pretty directly onto [the "participatory" adoption stage ](https://tag-app-delivery.cncf.io/whitepapers/platform-eng-maturity-model/#level-4-optimizing--participatory).

One way I would personally summarize the "adoption" stages is:
* Stage 1 - people use the platform erratically (people might not even know about it)
* Stage 2 - people use the platform because they have to / because there are top-down incentives to use it
* Stage 3 - people use the platform because they choose to
* Stage 4 - people not only use the platform, but contribute to it

And in that summary the innersource model you mention feels squarely in Stage 4.

However, I agree with @abangser that there's always a lot of iceberg under the surface when trying to map a specific organization or specific set of practices onto a general model like this one.

I'm referencing the "adoption" aspect here, rather than the "investment" aspect that you and @abangser reference. I think the "adoption" and "investment" aspects can generally be framed as "bottom-up" and "top-down", respectively, and I tend to view innersource models as "bottom-up", where people may choose to contribute to the organizaton's codebases but don't "have to" do so. So I go to "adoption" vs "investment" in that sense.

I'll echo Abby's questions, and especially this one:

> if you are inner sourcing as a sort of OSS code base that is single team governed, or if it is an ecosystem with more distributed ownership

That, to me, is maybe the most important element of this - the relationship between the platform team and the other teams that make contributions to the platform. Does the platform team see themselves (and does the organization see them) as "owners" of the platform, who accept occasional contributions from non-owners? Or do they see themselves more like "stewards" of a robust and sustaining ecosystem, where (potentially) the people outside the platform team are the "owners"?

**Comment by puja108** [comment]
Very much agree that "innersourcing" would be rather adoption category (or you could argue it also has some role in interface) and I'd add to that, that the maturity level especially in adoption depends not just on the fact that sth, here contribution, is available, it depends on if it's widely used. This is something that can then be measured and analyzed and if wanted be acted upon.

However, as Abby also mentioned these are not black and white good or bad. Continuing with contribution rate: It might be that contribution rate of single digit percentage of users is fully fine as long as your org is happy with it. One needs to also always look at the bigger picture, e.g. are people contributing because they are unhappy with how fast the platform team delivers and they feel blocked then high contribution rate might actually be an indicator that sth is wrong, or are they just super motivated and happy to work in the community and this does not distract them from their job then it is rather a good sign of adoption. Same measurement, very different story 😉  which is why some qualitative data next to quantitative sources is super important.

**Comment by abangser** [comment]
These are awesome points to bring in `adoption`.

I am curious @jkleinlercher, I would be keen to hear how these responses resonate with your experience / context? One of the things we most want to learn in this first phase post maturity model release is how it is being applied so this is the type of conversation I think everyone is excited to engage in!

**Comment by earth2marsh** [comment]
I've been playing with a GPT called [Platform Gardening](https://chat.openai.com/g/g-3CVJ1ZCWZ-platform-gardening) whose knowledge includes the platform maturity model and whitepaper. I thought it might be interesting to ask your question, and here was its response:

> In the context of the Platform Engineering Maturity Model, incorporating an "innersource" model, where people outside of the platform team can contribute to the platform, aligns most closely with "Level 4 - Enabled Ecosystem" of the Adoption aspect.
> 
> Here's why:
> 
> 1. **Participatory Ecosystem**: Level 4 in the Adoption aspect is characterized by a participatory ecosystem where users from product teams contribute back to the platform. This participation is not just in terms of feedback but also in terms of actual contributions, like improving existing capabilities or introducing new ones. This is a core principle of the innersource approach.
> 2. **Empowering Users to Contribute**: Innersource is about empowering all users to contribute, similar to how open source projects operate. This matches with the Level 4 idea where the platform is not just a service provided by a central team but a collaborative ecosystem that includes contributions from across the organization.
> 3. **Beyond Just Adoption**: Level 3 focuses more on intrinsic motivation for using the platform - where users are drawn to the platform due to its value in reducing cognitive load and providing high-quality services. While this level may include some degree of feedback and minor contributions from users, it doesn't necessarily imply a robust, active contribution model that is central to innersourcing.
> 4. **Strategic Extension of the Platform**: At Level 4, the platform is seen as a strategic asset that evolves through contributions from a broad range of stakeholders, aligning well with the innersource philosophy of open, collaborative development across organizational boundaries.
> 
> In summary, adopting an innersource model for your platform aligns with achieving a Level 4 - Enabled Ecosystem in the Adoption aspect of the Platform Engineering Maturity Model. It's about creating a participatory and collaborative environment where contributions to the platform are not just welcomed but actively encouraged from across the organization.

I think that is a decent application of the principles of the maturity model, but I have a slightly different overall take... It seems to me that innersourcing is an aspect of development culture that seems mostly independent of your platform approach. However, if the goal is to invite participation of teams in the platform you're building, then innersourcing might be a strategy you could pioneer with platform work if you weren't doing it already. In other words, I think these things are complementary, but that innersourcing is not necessarily a requirement of L4, though it may be a great stage to consider introducing it.

**Comment by abangser** [comment]
This issues has a lot of really great points and powerful voices. Is there anyone here who has the interest and vision for how to capture this in something we could publish as a blog? 💭

Just to say, this is not a suggestion that the discussion needs to be done here, more so that I would love to see this continued and offering an opportunity to make it available more widely if people have an interest!

**Comment by puja108** [comment]
That's a good idea. I'd be up for a blog post and open to colab on obe if someone else from this thread likes to join up.

**Comment by abangser** [comment]
Awesome! 🎉🎉

My suggestion would be to create a Google doc with global comment permissions and add collaborators as editors if/when they want to join.

You can share the doc here and then as it solidifies and is ready for posting it can become a PR.

**Comment by abangser** [comment]
In trying to get alignment on current WG priorities, I am going to suggest we close this topic. But before doing so, I want to give 1 week for anyone who is interested to revive the focus on this, else we can reopen in the future when we have the right people/energies to commit to this topic (or create an associated blog post).

Thanks!

**Comment by abangser** [comment]
Per my last message, I am closing for now but am happy to reopen this conversation if it becomes higher priority / has a sponsor to drive it!
