### ISSUE TITLE
Script: Platform Builder

### ISSUE THREAD

**Issue by mluskind** [cncf/tag-app-delivery#548]
### Motivation

- Create one re-usable artifact that can be used by any person interested in interviewing platform builders across companies.
- A consistent script will improve the integrity of the research and lead to comparable insights.

### Considerations
- What questions can we answer outside of the interview so maximize time for more valuable questions.
- Front-load most valuable questions (quality will be variable based on experience of interviewers in asking followup questions and staying within allotted time or extending the interview. 
- Interviewers are going to come with varying levels of experience conducting interviews. We can follow the observe, participate, lead model, to improve overall quality.
- Design in a way that would be applicable to platform builders (eng and PM) and platform leaders. It should be easy for the interviewer to jump to the right questions based on the interviewee.

### Outcomes
- A first usable iteration of the script that can be used by interviewers.

**Comment by mluskind** [comment]
Script Draft: https://docs.google.com/document/d/1TZl3zH5SrCzPR0SrKZ74LmmmUb8wb5z_J9rsj45YOho/edit#heading=h.y59stcex78yt

**Comment by bryanrossUK** [comment]
Great work on the script draft.  I didn't want to add any questions at this stage because it's probably already a struggle to get answers to all of these within the time frame.  However, I think there's a few angles that are important to platform as a product that are potentially missing:
* how broadly is the platform used across the organisation (a good product is ubiquitous) 
* how is the platform marketed to consumers?
* what help is available to consumers when adopting the platform?
* what regular communications do you have with consumers?

In my experience, I've found that teams can be quite good at developing new features when they're requested by a specific team.  They'll have lots of discussion with that one team on what is required, they'll add it to the roadmap, etc.  It feels very natural, because the organisation is usually well set up for project delivery.

What is often missing is how requests from across the broader consumer base are curated into the product vision, and then to create new features.  It's this idea of collecting and helping the broader userbase that I think is important to measure when we think about platform-as-a-product.  Likewise, how does the product team go about marketing themselves to other departments or business units - i.e. how do they proactively "grow the market".

I'd love to chat this through further if it's of interest.

**Comment by mluskind** [comment]
@bryanrossUK I couldn't agree more :) Take a look at the updated script: https://github.com/cncf/tag-app-delivery/blob/main/platform-as-a-product/platform-engineer-interview-script.md - let me know what you think.

**Comment by Rotfuks** [comment]
Here's the builder script: https://github.com/cncf/tag-app-delivery/blob/main/platform-as-a-product/platform-engineer-interview-script.md
