### ISSUE TITLE
Platforms Working Group has spanish text mixed with english

### ISSUE THREAD

**Issue by rynowak** [cncf/tag-app-delivery#631]
I just noticed the following on this page: https://tag-app-delivery.cncf.io/wgs/platforms/

<img width="1558" alt="image" src="https://github.com/cncf/tag-app-delivery/assets/1430011/50620a16-8b53-453d-ad6d-c8bc027c2519">

Notice that `Glosario` and its supporting text are in Spanish and the rest of the text is in English.

**Comment by abangser** [comment]
Great catch @rynowak and thanks for reporting! We have been refactoring how we managed languages and have had a few hiccups. 

I expect that this will be fixed with https://github.com/cncf/tag-app-delivery/issues/631 as I reviewed the preview deploy and it looks good there. 

Cc/ @lianmakesthings to confirm 💪

**Comment by lianmakesthings** [comment]
Should be fixed with https://github.com/cncf/tag-app-delivery/pull/628. I'm still waiting on approval from one of the other leads

**Comment by abangser** [comment]
Thanks again for the issue @rynowak. Just confirming what @lianmakesthings said, we have fixed a few niggles including this one with #625 and #628. Will close for now, but please reopen if you see continued issues. Thanks!
