### ISSUE TITLE
[Community] <Article: Enterprise IDP maturity hack: Infra. optimization>

### ISSUE THREAD

**Issue by Li-Or-Amir** [cncf/tag-app-delivery#643]
### Contribution Description

What do the Maturity Model, CNoE and Well-Architected all have in common?
All 3 can help enterprises navigate their way to an effective internal developer platform - and to cloud-native maturity in general. 
Zooming in on one domain - they all indicate the importance of baking infra. optimization (cost, resource efficiency, performance) into the IDP early on.
I believe this idea can contribute to the current discussion on "how not to spend oceans of money whilst building and maturing our platform". 

### Related Working Group (WG)

Platforms

### Contribution type

Blog (Default)

### Why TAG App Delivery?

This article is part of the effort to make platform engineering, a TAG app delivery project, more approachable for large enterprises that aren't necessarily cloud-native, and are financially conservative by nature. 

### Affiliation disclosure

I currently work as a product marketer at Spot by NetApp, an infra. optimization vendor.
Spot isn't directly mentioned.
However, my previous 2 articles around platform engineering, published on the Spot blog, are referenced:
https://spot.io/blog/platform-engineers-should-prioritize-infrastructure-optimization/
https://spot.io/blog/fresh-from-paris-platform-engineering-wisdom-from-kubecon/
As well as another blog discussing specific capabilities in greater depth.  

### Additional information

 
This article was written with some Plat.Eng.Day 2024 talks in mind, especially [Nicki's](https://www.youtube.com/watch?v=MiYn60VWtJk&t=1234s&pp=ygUQY25jZiBuaWNraSB3YXR0cw%3D%3D) and [Engin's](https://www.youtube.com/watch?v=4ODlmp4zMwY&t=345s&pp=ygUPY25jZiBlbmdpbiBkaXJp).

Draft attached - already reviewed by 2 engineers mentioned at the end and adjusted per their suggestions.
[TAG app delivery Enterprise IDPs maturity hacks.docx](https://github.com/cncf/tag-app-delivery/files/15168371/TAG.app.delivery.Enterprise.IDPs.maturity.hacks.docx)

**Comment by techmaharaj** [comment]
Hi @Li-Or-Amir thanks for submitting this outline. Possible to attach a Google Doc outline so that it'll be easy for everyone in the WG to contribute. If you have not joined the [wg-platforms slack channel](https://cloud-native.slack.com/archives/C020RHD43BP), you can do that and share the doc there as well.

**Comment by abangser** [comment]
+1 to Atul. @Li-Or-Amir we usually have some level of feedback on even blog posts (though the requirements to include feedback is more limited in this scope). You can do this either by sharing a google doc that provides ability to comment, or jumping straight to PR. Both works though we do find google docs allow for an easier set of convos as it is more interactive.

A couple of things I noted that would be easy fixes (and I can add to a shared doc if we start one) are:
* Ideally use `kubernetes` instead of `k8s` to enable better SEO
* We need to be aware when pushing forward a single project. So in the case where you have mentioned a project specifically, we usually ask that people provide at least 2 or 3 similar solutions.

Thanks again for submitting and look forward to collaboration and publishing!

**Comment by Li-Or-Amir** [comment]
@abangser thanks for your notes. Here's the google doc: https://docs.google.com/document/d/1fATY7nHGiQjJ4AZRzna198UJFc5bDLGC/edit?usp=sharing&ouid=102485578350250403020&rtpof=true&sd=true

Amendments made:
- Replaced k8s as suggested.
- Added 2 more platform tooling alternatives (this is the only place which specific projects are mentioned).

**Comment by abangser** [comment]
That's great, thanks so much @Li-Or-Amir. Now I will try to get a review in as well as maybe @techmaharaj or others. I hope we can review this week and get this posted asap!

**Comment by Li-Or-Amir** [comment]
Thanks ! 😄

**Comment by abangser** [comment]
Looks like there are just a few small comments in the doc @Li-Or-Amir, namely around the CNOE section being something that could use reflecting on the pattern rather than a single solution. Is this something you are open to including or would that change your intention too much? Once we clear that one way or another I think we can look for final review.

So @lianmakesthings / @angellk / @thschue please be aware we will be looking for TAG review shortly on this blog post (See: https://github.com/cncf/tag-app-delivery/issues/643#issuecomment-2095333557 for the google link)

**Comment by Li-Or-Amir** [comment]
@abangser I've seen @krumware 's input to the CNoE bit.
Tried to incorporate it in a way that underlines the relevance of CNoE without wildly digressing. 
If we're happy with the result, the comment can be resolved by the reviewers.
Thanks for working with me on this!

**Comment by abangser** [comment]
Hey @Li-Or-Amir, sorry for the delay. Are you comfortable opening a PR for this? I haven't heard any issue here so I'd like to get this published asap. 

[Here](https://cloud-native.slack.com/archives/C020RHD43BP/p1714675752028309?thread_ts=1713771793.512429&cid=C020RHD43BP) are some things I wrote up about blog PRs in the dish slack and feel free to reach out directly if I can help any more!

**Comment by Li-Or-Amir** [comment]
@abangser PMd on LI for help. Thanks!
